### ISSUE TITLE
Info on 'random' usage

### ISSUE THREAD

**Issue by Zankoas** [cwtools/cwtools-hoi4-config#107]
`random` used for events is in hours. This is really unclear and leads to a lot of mistakes as all the other fields there are in days.

PDX knows this and added in two new commands with 1.9: `random_hours` and `random_days`

They kept `random` as valid command to avoid breaking things backwards, but nevertheless it is a poor command. Using `random_hours` is much more clear and using `random_days` makes the whole thing more consistent.

I suggest firing an info on `random` to tell plays to switch to either of the new commands. Or, if we are being more drastic, simply dropping support for `random`.

**Comment by AngriestBird** [comment]
Addressed this in KR CWTools build. 

8dfd28e and b3c9835

**Comment by Zankoas** [comment]
Amazing, thanks!
