### ISSUE TITLE
`prerequisite` in focus section does not accept `OR`

### ISSUE THREAD

**Issue by inflation** [cwtools/cwtools-hoi4-config#116]
It's an alternative representation of "one of the prerequisites".
Examples:
```
prerequisite = { focus = GER_kdf_wagen OR = GER_synthetic_rubber }
```
I can't find a way to add to the rules either. It seems `cwtools` has a priority to choose `alias[effect:OR]` instead of plaintext `OR`.

**Comment by Zankoas** [comment]
@inflation What is the use case here? In what situation would you want to put `OR` there vs simply taking that out?

**Comment by Zankoas** [comment]
Two years late lol, but closing this in the absence of an answer
