### ISSUE TITLE
Updated Trigger Docs

### ISSUE THREAD

**Issue by CaesarVincens** [cwtools/cwtools-hoi4-config#13]
Updated Trigger docs from 1.6
[1_6_trigger_docs.txt](https://github.com/tboby/cwtools-hoi4-config/files/2949030/1_6_trigger_docs.txt)

**Comment by tboby** [comment]
I've generated the stubs for the new triggers/effects. The `replace_me`s will need expanding.

Weirdly, `remove_province_modifier` was missing from the trigger docs, but mentioned in the patch notes.

I can't see any mention of new scopes in the patch notes. Are there any?

**Comment by CaesarVincens** [comment]
I'm not sure, other than maybe something with admirals, but that shouldn't be much different from generals/field marshals except for the naval/land types of stuff. In any case, once I finally get my mod updated, I'll probably put some work in updating this stuff.

**Comment by CaesarVincens** [comment]
[1_7_trigger_docs.txt](https://github.com/tboby/cwtools-hoi4-config/files/3238975/1_7_trigger_docs.txt)
From the Beta
