### ISSUE TITLE
`on_daily_TAG` not recognised 

### ISSUE THREAD

**Issue by Zankoas** [cwtools/cwtools-hoi4-config#137]
The daily on action can have a tag adding as a suffix to only apply to that tag; `on_daily` turning into `on_daily_QIE` or something. We have support for `on_daily`, it just needs to be adjusted to also cover the tag based version

**Comment by Zankoas** [comment]
Still an issue sadly

**Comment by Pelmen323** [comment]
Fixed in the linked commit. Please close the report

**Comment by Zankoas** [comment]
And merged in, thanks @Pelmen323!
