### ISSUE TITLE
`operation_risk` false positive

### ISSUE THREAD

**Issue by Zankoas** [cwtools/cwtools-hoi4-config#138]
`operation_risk` is used in operation `risk_modifiers` in the following way:

`risk_modifiers = { operation_risk }`

Much like `operation_outcome` and `operation_cost` are used for `outcome_modifiers` and `cost_modifiers`. However, unlike those two, it isn't defined in `lar_operation_modifiers_pre_definition.txt`. In fact, it isn't defined anywhere:

![image](https://user-images.githubusercontent.com/24595951/84808006-f75fe680-afff-11ea-8d67-cac171f8e5f4.png)

So it seems there is something hardcoded going on here (or a PDX bug I guess).

Currently gives an error and probably shouldn't:

![image](https://user-images.githubusercontent.com/24595951/84808112-21190d80-b000-11ea-8c1f-51943afc7f7d.png)

**Comment by ICodeMaster** [comment]
Fix present in #153

**Comment by Zankoas** [comment]
Very nice, closed!
