### ISSUE TITLE
Capital Issue in History

### ISSUE THREAD

**Issue by AngriestBird** [cwtools/cwtools-hoi4-config#151]
In MD we have our history files scripted a bit different than vanilla (albeit they both work). 

![image](https://user-images.githubusercontent.com/12663269/93951402-39da4300-fd14-11ea-93af-f03699262e01.png)
![image](https://user-images.githubusercontent.com/12663269/93951424-48c0f580-fd14-11ea-90ec-30c387434f42.png)

Essentially, when you don't put capital outside of the history brackets (dates or otherwise) it errors all of the history files saying there is no capital command despite there being one in the history brackets. Its another style form so it should be included imo to lessen false-positive errors in either our mod or in others if they follow a similar convention for mods with many start dates.

**Comment by Zankoas** [comment]
Very late, but @AngriestBird can I check if this is still an issue?

**Comment by AngriestBird** [comment]
@Zankoas MD converted to vanilla standard. This can be disregarded.
