### ISSUE TITLE
Repeated alias' and interaction in CWTools CLI

### ISSUE THREAD

**Issue by ICodeMaster** [cwtools/cwtools-hoi4-config#154]
If an alias is repeated with the same name multiple times, CWTools Vscode treats the contents as separate alias' based on their contents. 
In CWTools CLI, it combines all duplicates of each alias into one rule, expecting each piece of **every** alias to be present.
Example:
![image](https://user-images.githubusercontent.com/4450978/96018033-bd211d00-0e18-11eb-96a2-f38c188e3136.png)

![image](https://user-images.githubusercontent.com/4450978/96018319-18530f80-0e19-11eb-8830-c4a47b5897f6.png)

This syntax is proper per the rule and does not throw an error in CWTools VScode. However the CLI verson does create errors based on the duplicated alias' shown here (ai_strategy_rule:ai_strategy) in `Config\common\ai_strategy.cwt`:
![image](https://user-images.githubusercontent.com/4450978/96018221-f8bbe700-0e18-11eb-8b6e-6690f7678538.png)

**Comment by Zankoas** [comment]
Very late here as well, but @ICodeMaster can I check if this is still an issue?

**Comment by Zankoas** [comment]
Nothing in a month, so going to close this one. Feel free to comment or open a new issue if it's still a problem. Thanks!
