### ISSUE TITLE
Some code that the checker does not recognize

### ISSUE THREAD

**Issue by masterbobli** [cwtools/cwtools-hoi4-config#158]
- [ ] 1. OR in prerequisite 

Eg. `prerequisite = { focus = GER_kdf_wagen OR = GER_synthetic_rubber }`

- [x] 2. Min / Max in randomize_temp_variable

Eg.
```
randomize_temp_variable = {
	var = num_dogs
	distribution = uniform
	min = 0
	max = 1
}
```

- [x] 3. Modifier `land_equipment_upgrade_xp_cost`

- [x] 4. Modifier `ai_desired_divisions_factor`

- [x] 5. Modifier `local_building_slots_factor`

**Comment by Zankoas** [comment]
1. is covered in this issue report here: https://github.com/cwtools/cwtools-hoi4-config/issues/116

**Comment by Zankoas** [comment]
3., 4., and 5. all seem to have been added now, very nice

**Comment by Zankoas** [comment]
The code for 2. is a nightmare to read; it seems as though it is covered though - and I haven't seen this issue recently, so I'm going to call it fixed. If it isn't please feel free to comment and I can take another look. Thanks for reporting!
