### ISSUE TITLE
Custom scripted_triggers are not recognised as triggers.

### ISSUE THREAD

**Issue by Makkkkus** [cwtools/cwtools-hoi4-config#165]
Scripted_triggers are not counted as triggers in this config. 

Example:
![image](https://user-images.githubusercontent.com/37084190/107145521-72389180-6942-11eb-89d6-6c0f12452eb7.png)

**Comment by Yard1** [comment]
Try reloading the window?

**Comment by Makkkkus** [comment]
That does not fix it

**Comment by Zankoas** [comment]
Very late to the party, but can I ask if this is still an issue?

**Comment by Makkkkus** [comment]
Doesn't look like it has been addressed, no.

**Comment by AngriestBird** [comment]
What file folder is this in? Is this in all allowed?

**Comment by Zankoas** [comment]
Ah. Yeah that's fair. I think best to close this report then given it's age; if you ever do start using it again feel free to open a new report. Thanks!
