### ISSUE TITLE
 Support HOI4 dynamic national focus and custom advisor slots

### ISSUE THREAD

**Issue by ArkhalisDragon** [cwtools/cwtools-hoi4-config#190]
If a focus is set dynamic,it's legal to write 2 or more icons in it.

![1](https://github.com/cwtools/cwtools-hoi4-config/assets/49909544/91689280-0bc1-487b-af5c-b4dcecb66247)

also the config now seems to not support custom advisor slots such as Kaiserreich
![2](https://github.com/cwtools/cwtools-hoi4-config/assets/49909544/98cd3096-c45f-4acd-b71a-7a267208bb3c)
![3](https://github.com/cwtools/cwtools-hoi4-config/assets/49909544/42d4b4d7-da44-4a2e-925c-193f2e38c5fc)

**Comment by Pelmen323** [comment]
I double-checked those issues:
- focus icons issue was resolved 8 months ago
![Screenshot (4432)](https://github.com/cwtools/cwtools-hoi4-config/assets/43440389/fd97fdd0-0f46-41b1-9425-20a6c58c177d)

- second_in_command was also resolved a long time ago
![Screenshot (4433)](https://github.com/cwtools/cwtools-hoi4-config/assets/43440389/6f49c9a6-d78f-440d-8dfb-fa894c1fc117)

Please do the following:
- Double-check that you use "latest" config rules
![Screenshot (4385)](https://github.com/cwtools/cwtools-hoi4-config/assets/43440389/f1c1d834-8acd-4186-8609-9a8c4ef65677)
- Double-check path to vanilla folder
- Regenerate vanilla cache (View -> Command Palette -> type "regenerate" and select "regenerate vanilla cache" option

If the issue will not be resolved, ping me here and I'll try to help
