### ISSUE TITLE
False positive for `forbid_equipment_type`, `allow_equipment_type`, `forbid_equipment_type_exact_match` - CW262

### ISSUE THREAD

**Issue by PPsyrius** [cwtools/cwtools-hoi4-config#194]
![image](https://github.com/cwtools/cwtools-hoi4-config/assets/19505219/3c45476b-3c42-4f29-8e89-241f5144da61)

We might want to at least hardcode allow the vanilla ones such as `anti_air`. `armor`, `flame`, `artillery`, `anti_tank`, `amphibious`

These entries also support multiple entries as well, here's some example from vanilla:
![image](https://github.com/cwtools/cwtools-hoi4-config/assets/19505219/461b4032-4203-4738-befc-c8fc96530d59)

**Comment by PPsyrius** [comment]
Could this be related to the recently closed #193 ?

**Comment by Pelmen323** [comment]
All fixed in https://github.com/Kaiserreich/cwtools-hoi4-config/commit/8aed02749be1177551ae830e4a688d63d17644c2
