### ISSUE TITLE
False positive for `fuel_capacity` stat in `expanded_fuel_tank` tank module - CW262

### ISSUE THREAD

**Issue by PPsyrius** [cwtools/cwtools-hoi4-config#195]
`fuel_capacity is unexpected in add_stats`

I did recheck and this does in fact exist in vanilla:
![image](https://github.com/cwtools/cwtools-hoi4-config/assets/19505219/76086692-1d2d-48f8-9630-2ce3294d3980)
![image](https://github.com/cwtools/cwtools-hoi4-config/assets/19505219/505e0c9d-f484-4e48-a9c9-21570bf53847)

**Comment by Pelmen323** [comment]
Fixed in https://github.com/Kaiserreich/cwtools-hoi4-config/commit/8aed02749be1177551ae830e4a688d63d17644c2
![Screenshot (4435)](https://github.com/cwtools/cwtools-hoi4-config/assets/43440389/550a2a63-bd6a-4566-a159-7d61b611ec2a)
