### ISSUE TITLE
'meta_effect' Unsupported

### ISSUE THREAD

**Issue by Zankoas** [cwtools/cwtools-hoi4-config#36]
`meta_effect ` supports more or less anything inside.

Likely will need a new data type in which just anything goes - @Yard1 

Example in code:
![image](https://user-images.githubusercontent.com/24595951/68143058-8bc18100-ff28-11e9-90f5-dc15e427e777.png)

**Comment by tboby** [comment]
You can now use `ignore_field` to handle this.
So, `meta_effect=  ignore_field` would match a clause with `meta_effect` on the left and anything inside!

**Comment by Zankoas** [comment]
Done and done
