### ISSUE TITLE
start_experience_factor in air_wings

### ISSUE THREAD

**Issue by DrNjitram** [cwtools/cwtools-hoi4-config#46]
Not expecting start_experience_factor in air_wings = { STATE_ID = { xxx }} blocks, at the xxx positions.
NOTE: multiple are possible, and need a defined air wing above them.
Example:
![afbeelding](https://user-images.githubusercontent.com/5411004/68552159-24b63780-0414-11ea-918f-28620815ddcd.png)
Ingame result is:
![afbeelding](https://user-images.githubusercontent.com/5411004/68552151-094b2c80-0414-11ea-8196-6edf6a4ca238.png)

**Comment by Yard1** [comment]
1c05da2015d0ec9db99e7313909400a92f39319c
