### ISSUE TITLE
Combat Tactic False positive

### ISSUE THREAD

**Issue by hiddengearz** [cwtools/cwtools-hoi4-config#54]
The following code is producing this error:  `tag used in wrong scope. In Combat but expect Country`

```
tactic_banzai_charge = { #Special Japan attacker tactic
	is_attacker = yes
	trigger = {
		tag = JAP
		is_attacker = yes
		phase = no
	}
	
	active = yes
	
	countered_by = tactic_overwhelming_fire
	
	base = { factor = 4 }
	picture = tactic_banzai_charge
	
	attacker_movement_speed = 0.1
	attacker = 0.25 
	defender = 0.1
}
```

This is valid HOI4 code and this is a vanilla example. 

I'm still learning how to modify the config but from what I see the issue is the scope. 

`## replace_scope = { this = combat root = combat from = combat }`

https://github.com/hiddengearz/cwtools-hoi4-config/blob/master/Config/common/combat_tactics.cwt#L15

How would one go about having multiple scopes?

edit:  Would it be `## scope = { combat country }` ?

**Comment by Yard1** [comment]
023875b
