### ISSUE TITLE
Allow for "dynamic" modifiers in modifiers.cwt

### ISSUE THREAD

**Issue by hiddengearz** [cwtools/cwtools-hoi4-config#57]
I recently made a pull request for some vanilla modifiers but these modifiers also extend to custom buildings, ideologies and etc found in mods and should be "dynamic".

```	
production_speed_air_base_factor = country
production_speed_anti_air_building_factor = country
production_speed_arms_factory_factor = country

communism_acceptance = country
communism_drift = country
democratic_acceptance = country
democratic_drift = country

```

If i created a building called test_building `production_speed_test_building_factor` would be valid but show as a F+ in CWTools.

If I created an ideology called nationalism nationalism `nationalism_acceptance` would be f+ in CWTools.

Can these be made dynamic? e.g `[ideology]_acceptance = country`

**Comment by Zankoas** [comment]
Same solution as for this report here: https://github.com/cwtools/cwtools-hoi4-config/issues/62

**Comment by Zankoas** [comment]
This seems to have been fixed, hell yeah!
