### ISSUE TITLE
Inbuilt Arrays Not Recognised

### ISSUE THREAD

**Issue by Alpinia** [cwtools/cwtools-hoi4-config#61]
![image](https://user-images.githubusercontent.com/51844377/70867047-a8050480-1f4f-11ea-93eb-e65b9294a432.png)

The following link has a list of game variables - there are several arrays mixed up in the lists.

**https://hoi4.paradoxwikis.com/Variables#Game_Variables**

**Comment by tboby** [comment]
Added here: https://github.com/cwtools/cwtools-hoi4-config/commit/b686b37451ee8a7c550b74f3cad600c6014622b0

If you find more hardcoded arrays, feel free to add them there (via PR :) ) and someone will probably just merge them!
