### ISSUE TITLE
HOI4 - Tag aliases not recognised

### ISSUE THREAD

**Issue by Alpinia** [cwtools/cwtools-hoi4-config#64]
A recent new function of HOI4 are tag aliases - they work like normal tags (three-letter codes), and all commands/triggers that accept tags also accept aliases. 
However, they are dynamic handles, which can be set dynamically based on event targets, variables, triggers or weighted random scoring.
![image](https://user-images.githubusercontent.com/51844377/71191946-25898700-2266-11ea-932c-890afee0b0c2.png)
In the image above, UPC is whatever tag is the UPC_leader global event target, and the same goes for NPA and npa_leader. ZHL and SZF are tag references that apply for the base SZC tag in specific conditions.

**Comment by Yard1** [comment]
Working on it

**Comment by Yard1** [comment]
ca2ad80faad43f543d07b42e52f693bf0beee836
