### ISSUE TITLE
Scripted GUIs Aren't Scanned

### ISSUE THREAD

**Issue by Zankoas** [cwtools/cwtools-hoi4-config#67]
So if a flag is set in one, it will give errors like this:

![image](https://user-images.githubusercontent.com/24595951/71263136-3525d000-2339-11ea-9352-d1a8a51f89b0.png)

Since it doesn't see that it has been set

**Comment by Yard1** [comment]
Needs rules written

**Comment by Yard1** [comment]
Done with f496a629d40d0e7d4b257ef60a709928aabac494
