### ISSUE TITLE
NOR tag thought as NOT-OR command

### ISSUE THREAD

**Issue by Zankoas** [cwtools/cwtools-hoi4-config#84]
Nice and simple bug here. CWTools is reading the NOR tag as the NOR command, which it isn't.

HOI4 sees NOT as NOR, so that NOR can be the tag for Norway.

Example of false error message here:
![image](https://user-images.githubusercontent.com/24595951/73483601-99579d00-4397-11ea-8b6d-1ed090133943.png)
![image](https://user-images.githubusercontent.com/24595951/73483608-9d83ba80-4397-11ea-8970-2e1049e8f9b5.png)

**Comment by tboby** [comment]
Pretty sure this is fixed

**Comment by Zankoas** [comment]
Can confirm it is fixed
